export const ServerActionTypes = {
  GET_SERVER_DATA: "GET_SERVER_DATA",
  GET_SERVER_DATA_SUCCESS: "GET_SERVER_DATA_SUCCESS",
  GET_SERVER_DATA_FAILURE: "GET_SERVER_DATA_FAILURE",
  CREATE_SERVER: "CREATE_SERVER",
  CREATE_SERVER_SUCCESS: "CREATE_SERVER_SUCCESS",
  CREATE_SERVER_FAILURE: "CREATE_SERVER_FAILURE",
  TOGGLE_CREATE_SERVER: "TOGGLE_CREATE_SERVER",
  ARRANGE_SERVER_LIST: "ARRANGE_SERVER_LIST",
  ARRANGE_SERVER_LIST_SUCCESS: "ARRANGE_SERVER_LIST_SUCCESS",
  ARRANGE_SERVER_LIST_FAILURE: "ARRANGE_SERVER_LIST_FAILURE",
};
